version: '3'

services:
  web:
    build: ./
    image: <%=appname%>:latest
    depends_on:
      - mysql
      - memcached
    networks:
      - default
      - proxy
    environment:
      - DB_NAME=wordpress
      - DB_USER=wordpress
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=mysql
      - ENVIRONMENT
      - AUTH_KEY
      - SECURE_AUTH_KEY
      - LOGGED_IN_KEY
      - NONCE_KEY
      - AUTH_SALT
      - SECURE_AUTH_SALT
      - LOGGED_IN_SALT
      - NONCE_SALT

  mysql:
    image: zolotoykod/mysql:latest
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD

  memcached:
    image: memcached:1.5-alpine
    volumes:
      - cache:/var/lib/memcached

volumes:
  mysql:
    driver: local
  cache:
    driver: local

networks:
  proxy:
    external: true
