version: '3'

services:
  web:
    build:
      dockerfile: Dockerfile-prod
    image: ${APP_IMAGE_NAME}
    environment:
      - WP_HOME=http://${DOMAIN}
    volumes:
      - uploads:/var/www/html/app/uploads/
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=${DOMAIN}
        - com.df.servicePath=/
        - com.df.port=80
      update_config:
        delay: 10s

volumes:
  uploads:
    driver: vsphere
    driver_opts:
      size: 2gb

  mysql:
    driver: vsphere
    driver_opts:
      size: 2gb

  cache:
    driver: vsphere
    driver_opts:
      size: 2gb

networks:
  proxy:
    external: true
