language: node_js
node_js:
  - node
  - 8
  - 7
  - 6
after_script: 'cat ./coverage/lcov.info | coveralls'

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email:
    recipients:
      - 1119@zolotoykod.ru
    on_success: never
    on_failure: always
