version: '3'

services:
  web:
    build:
      dockerfile: Dockerfile-prod
    image: ${APP_IMAGE_NAME}
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=${DOMAIN}
        - com.df.servicePath=/
        - com.df.port=80
      update_config:
        delay: 10s
<% if (includeMysql) { %>
volumes:
  mysql:
    driver: vsphere
    driver_opts:
      size: 2gb
<% } %>
networks:
  proxy:
    external: true
