stages:
  - test
  - prebuild
  - build
  - deploy

image: zolotoykod/build-tools:latest

test:
  stage: test
  image: node:alpine
  script:
    - make test
  cache:
    paths:
      - node_modules

frontend:
  stage: prebuild
  image: node:alpine
  script:
    - make frontend
  cache:
    paths:<% if (stack === 'node') { %>
      - www/public/node_modules
      - www/public/.awcache<% } else { %>
      - www/node_modules
      - www/.awcache<% } %>
  artifacts:
    paths:<% if (stack === 'node') { %>
      - www/public/dist<% } else { %>
      - www/dist<% } %>
  only:
    - tags
    - master

build:
  stage: build
  script:
    - make build
  only:
    - tags
    - master

staging:
  stage: deploy
  variables:
    DOMAIN: $CI_ENVIRONMENT_SLUG.$CI_PROJECT_PATH_SLUG.swarm.zolotoykod.ru
  script:
    - make deploy
  environment:
    name: staging
    url: http://$CI_ENVIRONMENT_SLUG.$CI_PROJECT_PATH_SLUG.swarm.zolotoykod.ru
  only:
    - master

production:
  stage: deploy
  variables:
    DOMAIN: $CI_ENVIRONMENT_SLUG.$CI_PROJECT_PATH_SLUG.swarm.zolotoykod.ru
  script:
    - make deploy
  environment:
    name: production
    url: http://$CI_ENVIRONMENT_SLUG.$CI_PROJECT_PATH_SLUG.swarm.zolotoykod.ru
  only:
    - tags
