version: '3'

services:
  app:
    build:
      dockerfile: Dockerfile-app
    image: ${APP_IMAGE_NAME}
    environment:
      - ENVIRONMENT
      - NODE_ENV
      - SITE_DOMAIN=${DOMAIN}
    volumes:
      - uploads:/home/node/www/public/uploads
    deploy:
      replicas: 1

  mongo:
    deploy:
      replicas: 1

  web:
    build:
      context: ./nginx/
    image: ${NGINX_IMAGE_NAME}
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=${DOMAIN}
        - com.df.servicePath=/
        - com.df.port=80
      update_config:
        delay: 10s

volumes:
  md:
    driver: vsphere
    driver_opts:
      size: 10gb
      fstype: xfs

  uploads:
    driver: vsphere
    driver_opts:
      size: 10gb
